In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
## Display all the columns of the dataframe

pd.pandas.set_option('display.max_columns',None)

In [97]:
data=pd.read_csv('/content/drive/MyDrive/heart_disease/heart_2020_cleaned.csv')

In [98]:
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

In [99]:
data.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [100]:
data['BMI']=np.where(data['BMI']<=18.5,1,data['BMI'])
data['BMI']=np.where((data['BMI']>18.5)&(data['BMI']<25.5),2,data['BMI'])
data['BMI']=np.where((data['BMI']>=25.5)&(data['BMI']<30.5),3,data['BMI'])
data['BMI']=np.where(data['BMI']>=30.0,4,data['BMI'])

In [101]:
x={
    1:'Underweight (BMI <= 18.5)',
   2:'Normal(BMI > 18.5 and <25.5)',
   3:'Overweight(BMI >=25.5 and BMI<30.0)',
   4:'Obese (BMI >= 30.0)'
}

In [102]:
data['BMI']=data['BMI'].map(x)

In [103]:
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,Underweight (BMI <= 18.5),Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,Normal(BMI > 18.5 and <25.5),No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,Overweight(BMI >=25.5 and BMI<30.0),Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,Normal(BMI > 18.5 and <25.5),No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,Normal(BMI > 18.5 and <25.5),No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

In [104]:
data.to_csv('/content/drive/MyDrive/heart_disease/heart_2020.csv')

In [63]:
data.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [105]:
categorical_features = [feature for feature in data.columns if data[feature].dtypes == 'O']
print('Number of categorical variables: ', len(categorical_features))

# visualise the numerical variables
data[categorical_features].head()

Number of categorical variables:  15

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,Asthma,KidneyDisease,SkinCancer
0,No,Underweight (BMI <= 18.5),Yes,No,No,No,Female,55-59,White,Yes,Yes,Very good,Yes,No,Yes
1,No,Normal(BMI > 18.5 and <25.5),No,No,Yes,No,Female,80 or older,White,No,Yes,Very good,No,No,No
2,No,Overweight(BMI >=25.5 and BMI<30.0),Yes,No,No,No,Male,65-69,White,Yes,Yes,Fair,Yes,No,No
3,No,Normal(BMI > 18.5 and <25.5),No,No,No,No,Female,75-79,White,No,No,Good,No,No,Yes
4,No,Normal(BMI > 18.5 and <25.5),No,No,No,Yes,Female,40-44,White,No,Yes,Very good,No,No,No

In [106]:
for feature in categorical_features:
  print(feature,"has : ",data[feature].unique()," values")

HeartDisease has :  ['No' 'Yes']  values
BMI has :  ['Underweight (BMI <= 18.5)' 'Normal(BMI > 18.5 and <25.5)'
 'Overweight(BMI >=25.5 and BMI<30.0)' 'Obese (BMI >= 30.0)']  values
Smoking has :  ['Yes' 'No']  values
AlcoholDrinking has :  ['No' 'Yes']  values
Stroke has :  ['No' 'Yes']  values
DiffWalking has :  ['No' 'Yes']  values
Sex has :  ['Female' 'Male']  values
AgeCategory has :  ['55-59' '80 or older' '65-69' '75-79' '40-44' '70-74' '60-64' '50-54'
 '45-49' '18-24' '35-39' '30-34' '25-29']  values
Race has :  ['White' 'Black' 'Asian' 'American Indian/Alaskan Native' 'Other'
 'Hispanic']  values
Diabetic has :  ['Yes' 'No' 'No, borderline diabetes' 'Yes (during pregnancy)']  values
PhysicalActivity has :  ['Yes' 'No']  values
GenHealth has :  ['Very good' 'Fair' 'Good' 'Poor' 'Excellent']  values
Asthma has :  ['Yes' 'No']  values
KidneyDisease has :  ['No' 'Yes']  values
SkinCancer has :  ['Yes' 'No']  values

#HeartDisease
Yes-1
No-0

In [107]:
data['HeartDisease']=data['HeartDisease'].replace(['No','Yes'],[0,1])

#Skincancer Asthma KidneyDisease Stroke DiffWalking Smoking AlcoholDrinking PhysicalActivity
Yes-1
No-0

#Sex
Male- 1
Female- 0

In [108]:
data['SkinCancer']=data['SkinCancer'].replace(['No','Yes'],[0,1])
data['Asthma']=data['Asthma'].replace(['No','Yes'],[0,1])
data['KidneyDisease']=data['KidneyDisease'].replace(['No','Yes'],[0,1])
data['Stroke']=data['Stroke'].replace(['No','Yes'],[0,1])
data['DiffWalking']=data['DiffWalking'].replace(['No','Yes'],[0,1])
data['Smoking']=data['Smoking'].replace(['No','Yes'],[0,1])
data['AlcoholDrinking']=data['AlcoholDrinking'].replace(['No','Yes'],[0,1])
data['Sex']=data['Sex'].replace(['Female','Male'],[0,1])

In [109]:
data['Race'].value_counts(ascending=False)

White                             245212
Hispanic                           27446
Black                              22939
Other                              10928
Asian                               8068
American Indian/Alaskan Native      5202
Name: Race, dtype: int64

#Race
White     -->                        1
Hispanic  -->                        2
Black     -->                        3
Other     -->                        4
Asian     -->                        5
American Indian/Alaskan Native -->   6

#GenHealth
Excellent --> 1
Very Good --> 2
Good --> 3
Fair --> 4
Poor --> 5

In [110]:
data['PhysicalActivity']=data['PhysicalActivity'].replace(['No','Yes'],[0,1])
data['GenHealth']=data['GenHealth'].replace(['Very good' ,'Fair', 'Good', 'Poor', 'Excellent'],[2,4,3,5,1])
data['Race']=data['Race'].replace(['White', 'Black','Asian', 'American Indian/Alaskan Native','Other',
                                   'Hispanic'],[1,3,5,6,4,2])

In [111]:
data['Diabetic'].value_counts(ascending=False)

No                         269653
Yes                         40802
No, borderline diabetes      6781
Yes (during pregnancy)       2559
Name: Diabetic, dtype: int64

#Diabetic
No            -->             1
Yes              -->           2
No, borderline diabetes  -->      3
Yes (during pregnancy)  -->     4

In [112]:
data['Diabetic']=data['Diabetic'].replace(['Yes', 'No', 'No, borderline diabetes', 'Yes (during pregnancy)'],[2,1,3,4])

In [113]:
d=data['AgeCategory'].value_counts().to_dict()

In [114]:
d

{'18-24': 21064,
 '25-29': 16955,
 '30-34': 18753,
 '35-39': 20550,
 '40-44': 21006,
 '45-49': 21791,
 '50-54': 25382,
 '55-59': 29757,
 '60-64': 33686,
 '65-69': 34151,
 '70-74': 31065,
 '75-79': 21482,
 '80 or older': 24153}

#AgeCategory
{'18-24' --> 21,
 '25-29' --> 27,
 '30-34' --> 32,
 '35-39' --> 37,
 '40-44' --> 42,
 '45-49' --> 47,
 '50-54' --> 52,
 '55-59' --> 57,
 '60-64' --> 62,
 '65-69' --> 67,
 '70-74' --> 72,
 '75-79' --> 77,
 '80 or older' --> 82}

In [115]:
d={'18-24': 21,
 '25-29': 27,
 '30-34': 32,
 '35-39': 37,
 '40-44': 42,
 '45-49': 47,
 '50-54': 52,
 '55-59': 57,
 '60-64': 62,
 '65-69': 67,
 '70-74': 72,
 '75-79': 77,
 '80 or older': 82}

In [116]:
data['AgeCategory']=data['AgeCategory'].map(d)

In [117]:
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,Underweight (BMI <= 18.5),1,0,0,3.0,30.0,0,0,57,1,2,1,2,5.0,1,0,1
1,0,Normal(BMI > 18.5 and <25.5),0,0,1,0.0,0.0,0,0,82,1,1,1,2,7.0,0,0,0
2,0,Overweight(BMI >=25.5 and BMI<30.0),1,0,0,20.0,30.0,0,1,67,1,2,1,4,8.0,1,0,0
3,0,Normal(BMI > 18.5 and <25.5),0,0,0,0.0,0.0,0,0,77,1,1,0,3,6.0,0,0,1
4,0,Normal(BMI > 18.5 and <25.5),0,0,0,28.0,0.0,1,0,42,1,1,1,2,8.0,0,0,0

In [118]:
data.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

x={
    1:'Underweight (BMI <= 18.5)',
   2:'Normal(BMI > 18.5 and <25.5)',
   3:'Overweight(BMI >=25.5 and BMI<30.0)',
   4:'Obese (BMI >= 30.0)'
}

In [119]:
data['BMI_Normal']=np.where(data['BMI']=='Normal(BMI > 18.5 and <25.5)',1,0)
data['BMI_Underweight']=np.where(data['BMI']=='Underweight (BMI <= 18.5)',1,0)
data['BMI_Overweight']=np.where(data['BMI']=='Overweight(BMI >=25.5 and BMI<30.0)',1,0)
data['BMI_Obese']=np.where(data['BMI']=='Obese (BMI >= 30.0)',1,0)

In [120]:
data.drop('BMI',axis=1,inplace=True)

Now as we saw previously our data is imbalanced so we will perform some sampling techniques. Here ve have done oversampling

In [121]:
columns = data.columns.tolist()
# Filter the columns to remove data we do not want 
columns = [c for c in columns if c not in ["HeartDisease"]]
# Store the variable we are predicting 
target = "HeartDisease"
# Define a random state 
state = np.random.RandomState(42)
X = data[columns]
Y = data[target]
# Print the shapes of X & Y
print(X.shape)
print(Y.shape)

(319795, 20)
(319795,)

In [122]:
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import NearMiss

In [123]:
smk = SMOTETomek(random_state=42)
X_res,y_res=smk.fit_resample(X,Y)

In [124]:
X_res.shape,y_res.shape

((584500, 20), (584500,))

In [125]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(Y)))
print('Resampled dataset shape {}'.format(Counter(y_res)))

Original dataset shape Counter({0: 292422, 1: 27373})
Resampled dataset shape Counter({0: 292250, 1: 292250})

In [126]:
## RandomOverSampler to handle imbalanced data

from imblearn.over_sampling import RandomOverSampler

In [127]:
os = RandomOverSampler(random_state=42)
X_train_res, y_train_res = os.fit_resample(X, Y)

In [128]:
X_train_res.shape,y_train_res.shape

((584844, 20), (584844,))

In [129]:
print('Original dataset shape {}'.format(Counter(Y)))
print('Resampled dataset shape {}'.format(Counter(y_train_res)))

Original dataset shape Counter({0: 292422, 1: 27373})
Resampled dataset shape Counter({0: 292422, 1: 292422})

In [130]:
X_res.tail()

,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,BMI_Normal,BMI_Underweight,BMI_Overweight,BMI_Obese
584495,0,0,0,0.000000,0.0,0,1,82,5,2,1,3,8.000000,0,0,0,1,0,0,0
584496,0,0,0,0.000000,0.0,0,1,77,1,1,1,2,7.000000,0,0,0,0,0,1,0
584497,0,0,0,20.000000,0.0,1,0,72,1,1,0,4,6.988203,1,0,0,0,0,0,1
584498,0,0,0,0.000000,10.0,0,0,47,1,1,1,2,4.572841,0,0,0,1,0,0,0
584499,1,0,0,0.141713,0.0,0,1,52,1,1,1,3,6.858287,0,0,0,0,0,1,0

In [131]:
X_res['HeartDisease']=y_res

In [132]:
X_res.head()

,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,BMI_Normal,BMI_Underweight,BMI_Overweight,BMI_Obese,HeartDisease
0,1,0,0,3.0,30.0,0,0,57,1,2,1,2,5.0,1,0,1,0,1,0,0,0
1,0,0,1,0.0,0.0,0,0,82,1,1,1,2,7.0,0,0,0,1,0,0,0,0
2,1,0,0,20.0,30.0,0,1,67,1,2,1,4,8.0,1,0,0,0,0,1,0,0
3,0,0,0,0.0,0.0,0,0,77,1,1,0,3,6.0,0,0,1,1,0,0,0,0
4,0,0,0,28.0,0.0,1,0,42,1,1,1,2,8.0,0,0,0,1,0,0,0,0

In [133]:
X_res.to_csv('/content/drive/MyDrive/heart_disease/heart_disease.csv')